name: Deploy

on:
  push:
    branches:
      - main  # veya hangi branch'ta deploy işlemi yapmak istiyorsanız o branch'in adını yazın

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Kullanmak istediğiniz Node.js versiyonunu belirtin

    - name: Install dependencies
      run: npm install

    - name: Run build script
      run: npm run build

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v1
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Firebase token'ınızı GitHub Secrets'te saklayın
